# Generated by Django 5.1 on 2024-08-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_grade_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.IntegerField(choices=[(10, '10'), (11, '11'), (12, '12')], default=10)),
                ('description', models.TextField()),
                ('bg_color', models.CharField(max_length=10)),
            ],
        ),
    ]
