# Generated by Django 5.1 on 2024-08-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_date_of_birth_customuser_date_of_births'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_of_births',
            new_name='date_of_birth',
        ),
    ]
