# Generated by Django 5.1 on 2024-08-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='password',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
