# Generated by Django 5.1 on 2024-08-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_classroom_password_classroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.TextField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
