# Generated by Django 5.1 on 2024-08-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_classroom_academic_year_classroom_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('teacher', 'name')},
        ),
    ]
