# Generated by Django 5.1 on 2024-08-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='classroom',
        ),
    ]
