# Generated by Django 5.1 on 2024-08-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_submission_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
