# Generated by Django 5.1 on 2024-08-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_studentfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfile',
            old_name='grade',
            new_name='score',
        ),
    ]
