# Generated by Django 5.1 on 2024-08-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='subsection_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='home.section')),
            ],
        ),
    ]
