# Generated by Django 5.1 on 2024-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
