# Generated by Django 5.1 on 2024-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_quizresult_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
