# Generated by Django 5.1 on 2024-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_quizresult_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answered_questions',
            field=models.IntegerField(default=0),
        ),
    ]
