# Generated by Django 5.1 on 2024-08-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_chatmessage_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='audio',
        ),
    ]
