# Generated by Django 5.1 on 2024-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_favoriteclassroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_sections',
            field=models.BooleanField(default=False),
        ),
    ]
