# Generated by Django 5.1 on 2024-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_customuser_notify_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
