# Generated by Django 5.1 on 2024-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_chatmessage_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
