# Generated by Django 5.1 on 2024-08-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_chatmessage_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quizresult')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.answer')),
            ],
        ),
    ]
