# Generated by Django 5.1 on 2024-08-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_answeredquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='allow_chat',
            field=models.BooleanField(default=True),
        ),
    ]
