# Generated by Django 5.1 on 2024-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_blockedparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedparticipant',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
