# Generated by Django 5.1 on 2024-08-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_forumpost_likes_forumpost_reason_forumpost_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
