# Generated by Django 5.1 on 2024-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_notificationsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=60)),
                ('subject', models.TextField(max_length=30)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
