# Generated by Django 5.1 on 2024-09-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
