# Generated by Django 5.1 on 2024-09-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_classroom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
