# Generated by Django 5.1 on 2024-09-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_studentfile_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username_changed',
            field=models.BooleanField(default=False),
        ),
    ]
