# Generated by Django 5.1 on 2024-09-28 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_customuser_username_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
