# Generated by Django 5.1 on 2024-09-28 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_forumpost_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='views_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
