# Generated by Django 5.1 on 2024-09-28 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_forumpost_views_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoTeacherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_teacher_requests', to='home.classroom')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_teacher_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
