# Generated by Django 5.1 on 2024-09-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_coteacherrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('co_teacher', 'Co-Teacher'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
