# Generated by Django 5.1 on 2024-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_days',
            field=models.IntegerField(default=0),
        ),
    ]
