# Generated by Django 5.1 on 2024-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_customuser_reset_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
