# Generated by Django 5.1 on 2024-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_submission_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsystem',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
        ),
        migrations.AddField(
            model_name='notificationsystem',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
