# Generated by Django 5.1 on 2024-10-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_notificationsystem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsystem',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('comment', 'Comment'), ('new_reg', 'New Registration'), ('content', 'Content')], default='message', max_length=50),
        ),
    ]
