# Generated by Django 5.1 on 2024-11-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alter_notificationsystem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsystem',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
