# Generated by Django 5.1.3 on 2024-12-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_notificationsystem_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
